public class GroupByAndHaving {
    //1.finding NUMBER OF STUDENTS BRANCH WISE
    //SELECT BRANCH ,COUNT(SID) FROM STUDENT GROUP BY BRANCH;
    //2.FINDING NUMBER OF MALE STUDENTS AND FEMALE STUDENTS
    //SELECT GENDER,COUNT(SID) FROM STUDENT GROUP BY GENDER;
    //3. FIND AVERAGE PERCENTAGE OF MALE STUDENTS AND FEMALE STUDENTS.
    //SELECT GENDER ,AVG(PERC) FROM STUDENT GROUP BY GENDER;
    //FIND THE MAXIMUM PERCENTAGE FROM MALE STUDENT AND FEMALE STUDENT
    // SELECT GENDER,MAX(PERC) FROM STUDENT GROUP BY GENDER;
    //FIND THE MINIMUM PERCENTAGE FROM MALE STUDENT AND FEMALE STUNDETS.
    // SELECT GENDER,MIN(PERC) FROM STUDENT GROUP BY GENDER;
    //FINDING BRANCHES HAVING ONLY ONE STUDENT
    //SELECT BRANCH,COUNT(BRANCH) FROM STUDENT GROUP BY BRANCH HAVING COUNT(SID)=1;
    //FINDING BRANCHES HAVING MORE THAN ONE STUDENTS
    //SELECT BRANCH,COUNT(BRANCH) FROM STUDENT GROUP BY BRANCH HAVIND COUNT(SID)>1;
    //FINDING THE BRANCHES IN WHICH STUDETN HAVING MIN PERCENTAGE IS GREATER THAN 70
  //SELECT BRANCH ,MIN(PERC) FROM STUDENT GROUP BY BRANCH HAVING MIN(PERC)>70;
    //FINDING THE BRANCHES IN WHICH STUDETN HAVING MAX PERCENTAGE IS GREATER THAN 90
   // SELECT BRANCH ,MAX(PERC) FROM STUDENT GROUP BY BRANCH HAVING MAX(PERC)>90;
}
