public class SqlQueries{
    //1. DISPLAY STUDENT DETAILS WHOSE PERCENTAGE >85
// SELECT * FROM STUDENT WHERE PERC>85;
//2. DISPLAY STUDENT DETAILS WHEERE PERCENTAGE .70 AND SID >103
// SELECT * FROM STUDENT WHERE PERC > 70 AND SID>103;
}
