public class SqlQueries{
    //1. DISPLAY STUDENT DETAILS WHOSE PERCENTAGE >85
// SELECT * FROM STUDENT WHERE PERC>85;
//2. DISPLAY STUDENT DETAILS WHOSE PERCENTAGE>70 AND SID >103
// SELECT * FROM STUDENT WHERE PERC > 70 AND SID>103;
 //3. DISPLAY STUDENT DETAILS WHOSE PERCENTAGE>70 OR SID>103
 //SELECT * FROM STUDENT WHERE PERC>70 OR SID>103;
 // 4. DISPLAY STUDENT DETAILS WHOSE PERCENTAGE NOT>90
    //SELECT * FROM STUDENT WHERE NOT PERC>70 ;
 // 5. DISPLAY STUDENT DETAILS IN ASCENDING OR DESCENDING BASED ON PERCENTAGE
    // SELECT * FROM STUDENT ORDER BY PERC; by default ASCENDING ORDER
    //SELECT 8 FROM STUDENT ORDER BY PERC DESC;
    // 6. DISPLAY STUDENT DETAILS IN ASCENDING OR DESCENDING BASED ON SNAME
    //SELECT * FROM STUDENT ORDER BY SNAME;
    // 7. DISPLAY FIRST 3 STUDENT DETAILS WHOSE PERCENTAGE>80
    //SELECT * FROM STUDENT WHERE PERC>80 LIMIT 3;
    //8. DISPLAY TOP 3 RANKERS BASED ON PERCENTAGE FROM THE STUDENT TABLE
    //SELECT * FROM STUDENT ORDER BY PERC DESC LIMIT 3;
    // DISPLAY STUDENT DETAILS WHOSE NAME STARTS WITH 'S'
    //SELECT * FROM STUDENT WHERE SNAME LIKE 'S%';
    //DISPLAY STUDENT DETAILS WHOSE NAME STARTS WITH S AND NOT REPEATED NAMES
    //SELECT DISTINCT SNAME FROM STUDENT WHERE SNAME LIKE 'S%'
}
