public class SqlQueries1 {
 //DISPLAY STUDENT DETAILS WHOSE NAME HAVE 'EE' ANYWHERE
    // SELECT * FROM STUDENT WHERE SNAME LIKE '%EE%'; HERE % MEANS MULTIPLE VALUES
    // DISPLAY STUDENT DETAILS WHOSE NAME ENDS WITH 'I'
    //SELECT * FROM STUDENT WHERE SNAME LIKE '%I';
    //DISPLAY STUDENT DETAILS WHOSE PERCENTAGE IS EITHER 90,99,88,75
    //SELECT * FROM STUDENT WHERE PERC IN(90,99,88,75);
    //DISPLAY STUDENT DETAILS WHOSE PERCENTAGE IS BETWEEN 85 AND 90
    //SELECT * FROM STUDENT WHERE PERC BETWEEN 85 AND 90;
}
