public class SqlQueries{
    //1. DISPLAY STUDENT DETAILS WHOSE PERCENTAGE >85
// SELECT * FROM STUDENT WHERE PERC>85;
//2. DISPLAY STUDENT DETAILS WHOSE PERCENTAGE>70 AND SID >103
// SELECT * FROM STUDENT WHERE PERC > 70 AND SID>103;
 //3. DISPLAY STUDENT DETAILS WHOSE PERCENTAGE>70 OR SID>103
 //SELECT * FROM STUDENT WHERE PERC>70 OR SID>103;
 // 4. DISPLAY STUDENT DETAILS WHOSE PERCENTAGE NOT>90
    //SELECT * FROM STUDENT WHERE NOT PERC>70 ;
 // 5. DISPLAY STUDENT DETAILS IN ASCENDING OR DESCENDING BASED ON PERCENTAGE
    // SELECT * FROM STUDENT ORDER BY PERC;
}
