public class UpdateAndDelete {
    // UPDATE THE STUDENT PERC TO 95 WHERE STUDENT NAME LATHA
    // UPDATE STUDENT SET PERC =95 WHERE SNAME = 'LATHA';
    // UPDATE THE STUDENT NAME TO VANI WHERE PERCENTAGE IS 78
    //UPDATE STUDENT SET SNAME = 'VANI' WHERE PERC = 78;
    // ADD COLUMN GRADE TO THE EXISTING STUDENT TABLE
    //ALTER TABLE STUDENT ADD GRADE VARCHAR(40);
    //UPDATE STUDENT GRADE TO PASS WHOSE SCORE IS GRTER THAN EQUAL TO 40 AND LESS THAN 65
    // UPDATE STUDENT SET GRADE = 'PASS' WHERE PERC>=40 AND PERC<=65;
    //UPDATE STUDENT SET GRADE='FIRST CLASS' WHERE PERC>=65 AND PERC<=70;
    //UPDATE STUDENT SET GRADE='DISTINCTION' WHERE PERC>70;
    //DELETE THE STUDENT ROW WHERE GRADE IS PASS
    // DELETE FROM STUDENT WHERE GRADE='PASS';
    //DELETE ALL THE ROWS OR RECORDS FROM STUDENT TABLE
    //DELETE FROM STUDENT;
    // COUNT THE SNAME FROM STUDENT TABLE
    //SELECT COUNT(SNAME) FROM STUDENT;
    // GET THE TOTAL OF PERC FROM STUDENT TABLE
    //SELECT SUM(PERC) FROM STUDENT;
    //GET THE MIN VALUE IN PERC FROM STUDENT TABLE
    //SELECT MIN(PERC) FROM STUDENT;
    //SELECT MAX(PERC) FROM STUDENT;
    //GET THE COUNT FROM THE BRANCH WHICH IS NOT REPETITIVE FROM STUDENT TABLE
    //SELECT COUNT(DISTINCT BRANCH) FROM STUDENT; // AS PER TABLE 3 BRANCHES CIVIL,CSE,ECE.
    //SELECT COUNT (DISTINCT GENDER) FROM STUDENT;


}
